import type { PoolClient } from 'pg';

/**
 * This migration adds the necessary tables to store and manage
 * inter-provider swap recommendations generated by the workload
 * balancing engine.
 */
export async function up(client: PoolClient): Promise<void> {
  await client.query(`
    CREATE TABLE IF NOT EXISTS swap_recommendations (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      provider_a_id UUID NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
      provider_b_id UUID NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
      location_a_to_b_id UUID NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
      location_b_to_a_id UUID NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
      value_a_to_b_monthly NUMERIC(10, 2) NOT NULL,
      value_b_to_a_monthly NUMERIC(10, 2) NOT NULL,
      net_value_change_a NUMERIC(10, 2) NOT NULL,
      net_value_change_b NUMERIC(10, 2) NOT NULL,
      efficiency_gain_miles NUMERIC(10, 2),
      status VARCHAR(20) NOT NULL DEFAULT 'pending', -- pending, accepted, rejected
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      reviewed_by UUID REFERENCES users(id),
      reviewed_at TIMESTAMP WITH TIME ZONE
    );
  `);

  await client.query(`CREATE INDEX IF NOT EXISTS idx_swap_recommendations_status ON swap_recommendations(status);`);
  await client.query(`CREATE INDEX IF NOT EXISTS idx_swap_recommendations_provider_a ON swap_recommendations(provider_a_id);`);
  await client.query(`CREATE INDEX IF NOT EXISTS idx_swap_recommendations_provider_b ON swap_recommendations(provider_b_id);`);

  console.log('Created "swap_recommendations" table.');
}
